# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2019-06-24T05:07:18Z"
  generation: 3
  labels:
    run: simple-svc
  name: simple-svc
  namespace: default
  resourceVersion: "15959"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/simple-svc
  uid: f078b14e-963d-11e9-aa9e-080027b33716
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: simple-svc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: simple-svc
    spec:
      containers:
      - image: briandowns/simple-svc:latest
        imagePullPolicy: Always
        name: simple-svc
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always

