kind: Service
apiVersion: v1
metadata:
  name: simple-api-svc
spec:
  selector:
    app: simple-svc
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: simple-api-svc
subsets:
  - addresses:
      - ip: 192.168.0.222
    ports:
      - port: 80