kind: Service
apiVersion: v1
metadata:
  name: simple-api-svc
spec:
  selector:
    app: simple-svc
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
